### ISSUE TITLE
Definir motores

### ISSUE THREAD

**Issue by afr2903** [RoBorregos/sumo-bot#1]
Definir que motores son los mas adecuados para el **robot**

**Opcion 1**
![image](https://github.com/RoBorregos/sumo-bot/assets/25570636/92a8be76-e428-42d7-96ce-2b6e68101d7a)

**Opcion 2**
![image](https://github.com/RoBorregos/sumo-bot/assets/25570636/ccec50a8-d9fc-4b85-a1bb-89ded24f6815)

**Comment by Yair-Reyes** [comment]
Se eligieron los **Pololu** por calidad/precio
